name: "Run tests on Bun"

on:
  push:
    paths:
      - ".github/workflows/bun.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/bun.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vite-version: ["vite@5", "vite@6", "vite@7"]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 10

      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        name: Set up Bun cache
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          bun install
          bun install ${{ matrix.vite-version }}

      - name: Lint Source
        run: bun run --if-present lint

      - name: Build Source
        run: bun run --if-present build

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run Tests
        run: bun run --if-present test
