name: "Run tests on Deno"

on:
  push:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vite-version: ["vite@5", "vite@6", "vite@7"]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 10

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        name: Set up Deno cache
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Vite
        run: |
          deno cache npm:${{ matrix.vite-version }} \
            --allow-scripts \
            --no-lock \
            --node-modules-dir=auto

      - name: Lint Source
        run: deno lint --ignore=node_modules **/*.ts

      # - name: Install Playwright browsers
      #   run: deno run --allow-all npm:playwright install --with-deps

      - name: Run Tests
        run: |
          deno run --allow-all npm:vitest run --exclude e2e
          # deno run --allow-all npm:playwright test
